# --- AUTH API's ----
#### Create   User
POST http://localhost:8888/ecommerce_api/api/register
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 38|LsdiHC1b4r8flS9i8LfPbvFSTMsbecQfIetKSeuh

{
    "name": "emma",
    "email": "felx@gmail.com",
    "password": "admin123",
    "role" : 5
}



#### Get All Users
GET http://localhost:8888/ecommerce_api/api/users
Content-Type: application/json
Accept: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI0Mjc5NjQ1LCJleHAiOjE2MjQzNjYwNDV9.ZlfzRFq5CuPx3vUXIuYrAVnempRc5CfwB7FIcdgeDf0

#### Get User By Id
GET http://localhost:8888/ecommerce_api/api/users/9
Content-Type: application/json
Accept: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI0Mjc5NjQ1LCJleHAiOjE2MjQzNjYwNDV9.ZlfzRFq5CuPx3vUXIuYrAVnempRc5CfwB7FIcdgeDf0



#### Update User By Id
PUT http://localhost:8888/ecommerce_api/api/users/6
Content-Type: application/json
Accept: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI0Mjc5NjQ1LCJleHAiOjE2MjQzNjYwNDV9.ZlfzRFq5CuPx3vUXIuYrAVnempRc5CfwB7FIcdgeDf0

{
    "name": "francis",
    "email": "francis477@gmail.com",
    "roles" : "superadmin"
}


#### Delete User By Id
DELETE  http://localhost:8888/ecommerce_api/api/delete_user/8
Content-Type: application/json
Accept: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI0Mjc5NjQ1LCJleHAiOjE2MjQzNjYwNDV9.ZlfzRFq5CuPx3vUXIuYrAVnempRc5CfwB7FIcdgeDf0


#### Login
POST http://localhost:8888/ecommerce_api/api/auth
Content-Type: application/json
Accept: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI0Mjc5NjQ1LCJleHAiOjE2MjQzNjYwNDV9.ZlfzRFq5CuPx3vUXIuYrAVnempRc5CfwB7FIcdgeDf0

{
    "email": "francisteye477@gmail.com",
    "password": "admin123"
}


#### logout User
POST http://localhost:8888/ecommerce_api/api/logout
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 35|5Exef5PGvJQvgkvJo3WnZrHRguLrzbsNmjAlWFhw
