# --- AUTH API's ----
#### Login
POST http://localhost:8888/ecommerce_api/api/auth
Content-Type: application/json
Accept: application/json

{
    "email": "francisteye477@gmail.com",
    "password": "admin123"
}


#### Get User Profile By ID
GET http://localhost:8888/ecommerce_api/api/profile/1
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 1|AoDX3H0SxiZKE7qodLaTopRHLqSfijREJkvo5pjs


#### Update User Profile By ID
PUT http://localhost:8888/ecommerce_api/api/profile/1
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 1|AoDX3H0SxiZKE7qodLaTopRHLqSfijREJkvo5pjs

{
     "name": "francis Teye",
    "email": "francisteye477@gmail.com"

}

#### Change User Password  By ID
PUT http://localhost:8888/ecommerce_api/api/change_password/1
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 1|AoDX3H0SxiZKE7qodLaTopRHLqSfijREJkvo5pjs

{
    "old_pass": "admin9095",
    "new_pass": "admin123"
}


#### logout User
POST http://localhost:8888/ecommerce_api/api/logout
Accept: application/json
Authorization: "Bearer 13|SbvCzi6ZByTFyaUGejKXX1XHsS81O0RKt3Qk6cpr
Content-Type: application/json
