# --- ROLE API's ----
#### Create   Role
GEt http://localhost:8888/ecommerce_api/api/category?page=1&size=2
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 5|hPXnxxUV35EGFioYRLbFhbmz92Ygx2Dp3ssJ6o4i



#### Assign Role To  Permissions
POST http://localhost:8888/ecommerce_api/api/create_category
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 20|R5wEOxMpvnrH89J2Bb2Dw3cKOUTZgdG3x2I3FxdQ

{
    "name": "Product One"

}


#### Show Category By Id
GET http://localhost:8888/ecommerce_api/api/category/1
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 1|wtvDXSYxo3HdLsXjFsBHRPV8TLuJBm5HqepNxwuZ

#### Update Category By Id
PUT http://localhost:8888/ecommerce_api/api/category/1
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 1|wtvDXSYxo3HdLsXjFsBHRPV8TLuJBm5HqepNxwuZ

{
    "name": "Product One Updated"
}


#### Delete Role
DELETE http://localhost:8888/ecommerce_api/api/category/1
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 1|wtvDXSYxo3HdLsXjFsBHRPV8TLuJBm5HqepNxwuZ

