# --- PRODUCT API's ----
#### Update   Product
PUT http://localhost:8888/ecommerce_api/api/update_product/1
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 5|hPXnxxUV35EGFioYRLbFhbmz92Ygx2Dp3ssJ6o4i
{
    "pro_name": "ProductOne",
    "pro_price": "233.00",
    "pro_details": "Updated Product Details One",
    "pro_stock" : 1,
    "category_id" : 1,
    "rating" : 1,
    "brand_id" : 1


}



#### Get All  Product
GET http://localhost:8888/ecommerce_api/api/all_product_two
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 5|hPXnxxUV35EGFioYRLbFhbmz92Ygx2Dp3ssJ6o4i



#### Get All  Product
GET http://localhost:8888/ecommerce_api/api/all_product?sortBy=id&sortOrder=desc&paginate=1&perpage=10
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 5|hPXnxxUV35EGFioYRLbFhbmz92Ygx2Dp3ssJ6o4i




#### Get All  Home Product
GET http://localhost:8888/ecommerce_api/api/home_product/
Content-Type: application/json
Accept: application/json


### Get All  Product
GET http://localhost:8888/ecommerce_api/api/all_product?sortBy=id&sortOrder=desc&paginate=1&perpage=10&minPrice=&maxPrice=
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 5|hPXnxxUV35EGFioYRLbFhbmz92Ygx2Dp3ssJ6o4i


#### Delete Product
DELETE  http://localhost:8888/ecommerce_api/api/delete_product/106
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 1|wtvDXSYxo3HdLsXjFsBHRPV8TLuJBm5HqepNxwuZ


#### Delete Product
GET  http://localhost:8888/ecommerce_api/api/all_images/3
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 2|G54J9X8d4KpxKwOyaLwayWJRZsLGVoaWz0sZFNKO
