# --- USER API's ----
#### Create   User
POST http://localhost:8888/ecommerce_api/api/register
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 2|p207qRw5Sj2UjIWVVkBdGvIEbNZjE88HjPaIv5Uv

{
    "name": "emma",
    "email": "emma@gmail.com",
    "password": "admin123",
    "role" : 1
}



#### Get All Users
GET http://localhost:8888/ecommerce_api/api/users
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 2|p207qRw5Sj2UjIWVVkBdGvIEbNZjE88HjPaIv5Uv

#### Get User By Id
GET http://localhost:8888/ecommerce_api/api/users/2
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 2|p207qRw5Sj2UjIWVVkBdGvIEbNZjE88HjPaIv5Uv



#### Update User By Id
PUT http://localhost:8888/ecommerce_api/api/users/1
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 2|p207qRw5Sj2UjIWVVkBdGvIEbNZjE88HjPaIv5Uv

{
    "name": "francis",
    "email": "francis477@gmail.com",
    "roles" : 1
}


#### Delete User By Id
DELETE  http://localhost:8888/ecommerce_api/api/delete_user/8
Content-Type: application/json
Accept: application/json
Authorization:  Bearer 2|p207qRw5Sj2UjIWVVkBdGvIEbNZjE88HjPaIv5Uv


